drl_param:
  batch_size: 128
  buffer_size: 15000
  gamma: 0.9
  minimal_size: 200
  target_entropy: -1
  tau: 0.005
env_config:
  action:
    type: DiscreteMetaAction
  centering_position:
  - 0.3
  - 0.5
  collision_reward: -10
  controlled_vehicles: 1
  desire_speed: 28
  duration: 180
  ego_spacing: 2
  high_speed_reward: 0.5
  initial_lane_id: null
  lane_change_reward: 0
  lanes_count: 4
  manual_control: false
  normalize_reward: true
  observation:
    absolute: false
    features:
    - presence
    - x
    - y
    - vx
    - vy
    features_range:
      vx:
      - -30
      - 30
      vy:
      - -30
      - 30
      x:
      - -100
      - 100
      y:
      - -100
      - 100
    normalize: true
    order: sorted
    type: Kinematics
    vehicles_count: 6
  offroad_terminal: true
  offscreen_rendering: false
  other_vehicles_type: highway_env.vehicle.behavior.IDMVehicle
  policy_frequency: 1
  real_time_rendering: false
  render_agent: true
  reward_speed_range:
  - 20
  - 30
  right_lane_reward: 0.05
  safety_reward: -0.05
  scaling: 5.5
  screen_height: 150
  screen_width: 600
  show_trajectories: false
  simulation_frequency: 15
  vehicles_count: 50
  vehicles_density: 1
learning_rate:
  actor_lr: 0.0005
  alpha_lr: 0.005
  critic_lr: 0.005
train_episodes: 5000
